# Pulls electricity data from the EIA API v2 and saves CSVs.
# What this does:
#   1. Connects to the EIA API using API key from .env
#   2. Fetches retail electricity prices by state (cents/kWh)
#   3. Fetches generation by fuel source (coal, gas, solar, wind)
#   4. Saves each dataset to data/raw/

 
import os
import requests
import pandas as pd
from dotenv import load_dotenv
from pathlib import Path
import time
from typing import List, Dict, Optional
 
# Load your API key from the .env file
load_dotenv()
 
 
class EIADataFetcher:
    """Handles all communication with the EIA API v2."""
    
    def __init__(self, api_key: Optional[str] = None):
        """Load API key, set base URL and shared session."""
        self.api_key = api_key or os.getenv("EIA_API_KEY")
        if not self.api_key:
            raise ValueError("EIA_API_KEY not found. Add it to your .env file.")
        
        # EIA API v2 — all data endpoints end in /data
        self.base_url = "https://api.eia.gov/v2"
        self.rate_limit_delay = 0.5
        self.session = requests.Session()
    
    def _make_request(self, endpoint: str, params: Dict) -> Dict:
        """
        Core request function.
        Attaches API key, rate limits, calls the API, returns JSON.
        """
        params["api_key"] = self.api_key
        url = f"{self.base_url}{endpoint}"
        
        time.sleep(self.rate_limit_delay)
        response = self.session.get(url, params=params)
        
        print(f"  Calling: {response.url[:90]}...")
        response.raise_for_status()
        return response.json()
    
   
    # FETCH #1: RETAIL ELECTRICITY PRICES
    # Monthly average retail price (cents/kWh) by state + sector
    # TARGET VARIABLE, this is what we want to predict

    def fetch_electricity_prices(self, states: List[str] = None,
                                  save_path: str = "data/raw/electricity_prices.csv") -> pd.DataFrame:
        """
        Fetch retail electricity prices by state, monthly.
 
        Endpoint: /v2/electricity/retail-sales/data
        Key column: price (cents per kWh)
        Sectors: RES=residential, COM=commercial, IND=industrial, ALL=combined
        """
        print("\nFetching electricity prices...")
        
        params = {
            "frequency": "monthly",
            "data[0]": "price",            # cents per kWh — our target variable
            "data[1]": "sales",            # MWh sold — useful context
            "facets[sectorid][0]": "RES",  # residential sector
            "facets[sectorid][1]": "COM",  # commercial sector
            "facets[sectorid][2]": "IND",  # industrial sector
            "sort[0][column]": "period",
            "sort[0][direction]": "desc",  # most recent first
            "offset": 0,
            "length": 5000
        }
        
        # Add state filters, as EIA uses indexed facets for multiple values
        if states:
            for i, state in enumerate(states):
                params[f"facets[stateid][{i}]"] = state
        
        try:
            # Note: /data at the end, required for actual records in EIA v2
            response = self._make_request("/electricity/retail-sales/data", params)
        except requests.exceptions.RequestException as e:
            print(f"  Error: {e}")
            return pd.DataFrame()
        
        if "response" not in response or "data" not in response["response"]:
            print("  Unexpected response structure:")
            print(response)
            return pd.DataFrame()
        
        df = pd.DataFrame(response["response"]["data"])
        df.columns = df.columns.str.lower()
        
        # Convert price to numeric (comes back as string from API)
        if 'price' in df.columns:
            df['price'] = pd.to_numeric(df['price'], errors='coerce')
        
        # Split "YYYY-MM" period into year and month columns
        if 'period' in df.columns:
            df['year'] = df['period'].str[:4].astype(int)
            df['month'] = df['period'].str[5:7].astype(int)
            df = df.drop('period', axis=1)
        
        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(save_path, index=False)
        print(f"  Saved {len(df)} rows to {save_path}")
        print(f"  Columns: {list(df.columns)}")
        
        return df
    
   
    # FETCH #2: GENERATION BY FUEL SOURCE
    # Monthly MWh generated by coal, gas, solar, wind, etc.
    # KEY PREDICTOR — generation mix strongly influences price
   
    def fetch_generation_by_source(self, states: List[str] = None,
                                    save_path: str = "data/raw/generation_by_source.csv") -> pd.DataFrame:
        """
        Fetch electricity generation (MWh) by fuel type and state, monthly.
 
        Endpoint: /v2/electricity/electric-power-operational-data/data
        Key column: generation (MWh)
        Fuel types: COL=coal, NG=natural gas, SUN=solar, WND=wind,
                    NUC=nuclear, HYC=hydro, PET=petroleum
        """
        print("\nFetching generation by fuel source...")
        
        params = {
            "frequency": "monthly",
            "data[0]": "generation",       # MWh generated
            "sort[0][column]": "period",
            "sort[0][direction]": "desc",
            "offset": 0,
            "length": 5000
        }
        
        # Filter to electric utilities only (sector 1 = electric utility)
        params["facets[sectorid][0]"] = "1"
        
        if states:
            for i, state in enumerate(states):
                params[f"facets[location][{i}]"] = state
        
        try:
            response = self._make_request("/electricity/electric-power-operational-data/data", params)
        except requests.exceptions.RequestException as e:
            print(f"  Error: {e}")
            return pd.DataFrame()
        
        if "response" not in response or "data" not in response["response"]:
            print("  Unexpected response structure:")
            print(response)
            return pd.DataFrame()
        
        df = pd.DataFrame(response["response"]["data"])
        df.columns = df.columns.str.lower()
        
        if 'generation' in df.columns:
            df['generation'] = pd.to_numeric(df['generation'], errors='coerce')
        
        if 'period' in df.columns:
            df['year'] = df['period'].str[:4].astype(int)
            df['month'] = df['period'].str[5:7].astype(int)
            df = df.drop('period', axis=1)
        
        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(save_path, index=False)
        print(f"  Saved {len(df)} rows to {save_path}")
        print(f"  Columns: {list(df.columns)}")
        
        return df
 
 

# MAIN

def main():
    fetcher = EIADataFetcher()
    
    target_states = ["CA", "TX", "CO", "NY", "IL"]
    
    print(f"Fetching data for: {target_states}")
    print("=" * 50)
    
    prices_df     = fetcher.fetch_electricity_prices(states=target_states)
    generation_df = fetcher.fetch_generation_by_source(states=target_states)
    
    print("\n" + "=" * 50)
    print("Done!")
    print(f"  Prices shape:     {prices_df.shape}")
    print(f"  Generation shape: {generation_df.shape}")
    
    if not prices_df.empty:
        print("\n--- Prices Preview ---")
        print(prices_df.head(10))
    
    if not generation_df.empty:
        print("\n--- Generation Preview ---")
        print(generation_df.head(10))
 
 
if __name__ == "__main__":
    main()